name: actions-metrics-otlp
description: capture github actions metrics

inputs:
  github-token:
    description: GitHub token to get jobs and steps if needed
    default: ${{ github.token }}
    required: true
  github-token-rate-limit-metrics:
    description: GitHub token for rate limit metrics
    default: ${{ github.token }}
    required: true

  collect-job-metrics:
    description: Collect job metrics
    required: false
    default: 'false'
  collect-step-metrics:
    description: Collect step metrics
    required: false
    default: 'false'

  exporter:
    description: the OTEL exporter to use. supported values - gcp, console
    required: true

  gcp-project-id:
    description: Explicitly set GCP Project ID, for use with "gcp" exporter. Otherwise, project will be inferred.
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
